### PR TITLE
Fix Input Leap icon for Wayland

### LINKED ISSUE #1802: Incorrect app id matching for .desktop icon in Wayland
### What happened?

In Wayland session the app shows generic icon. To correctly display the icon in Wayland session desktop file should provide correct app id. IUUC it should be named like com.github.input-leap.desktop or contain "StartupWMClass=com.github.input-leap" in "Desktop entry". Not sure what's the correct way to make it proper.

Before:

Screenshot from 2023-12-21 01-34-23

After:

Screenshot from 2023-12-21 01-39-35

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

3e681454

### If applicable, where did you install Input Leap from?

self built install with patches to allow to run in native Wayland.

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland

### What OS versions are you using?

Arch Linux, GNOME 45

### Relevant log output

_No response_

### Any other information

_No response_

### PR DESCRIPTION
**Pull request by sithlord48**
- Simplify CMake conditionals (legacy code)
- Make the application aware of its desktop file.
- Rename icon and desktop to correct Appstream names.

Fixes #1802.
Closes #1805 (supersedes PR).

## Contributor Checklist:

* [ ] I have created a file in the `doc/newsfragments` directory *IF* it is a
      user-visible change (and make sure to read the `README.md` in that directory)

### CODE REVIEW

**Comment by darkblaze69** [comment]
I confirm, now it looks good in Wayland, not tested in X11.

image

**Comment by shymega** [comment]
@sithlord48 Probably best for this PR to supersede mine.

However, I can't merge it, because it's based on my commit, and represents the authorship incorrectly.

Can you please recreate the HEAD commit with your name, same description, and your PGP sig?

Cheers. Then I'll merge.

**Comment by sithlord48** [comment]
Ok should be signed and based proper for landing @shymega

**Comment by shymega** [comment]
Rebased against `master`, edited PR desc and edited commit to detail changes.

Newsfragment might be necessary, but we can always add that at a later date. I'd like to get this merged ASAP.

Merging now.

**Pull request merged**
