### PR TITLE
Alter clean_build.sh to build on macOS.

### PR DESCRIPTION
**Pull request by ghost**
> This PR has been migrated from old Barrier Github repository https://github.com/debauchee/barrier/pull/1243
> 
> PR created on: 2021-08-10 by @go8ose
> PR last updated on: 2021-11-05

This is the change that haken-theren suggested in bug #756, to allow building of barrier on macOS.

---

> Commented on: 2021-08-11 by @go8ose

Hmm. Maybe the next step is to patch the clean_build.sh script so that my change only occurs for Catalina and later systems.

---

> Commented on: 2021-08-19 by @shymega

If anyone has a Mac device, we'd welcome tests on various versions of the OS in relation to this PR...

---

> Commented on: 2021-08-19 by @fdelucchijr

I have macOS M1 MBA, happy to test it. At first glance gets this:

```
CMake Error at /opt/homebrew/Cellar/cmake/3.20.5/share/cmake/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/../Documents/Proyects/BarrierNative/orignial/barrier/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make -f Makefile cmTC_560a4/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_560a4.dir/build.make CMakeFiles/cmTC_560a4.dir/build
    Building C object CMakeFiles/cmTC_560a4.dir/testCCompiler.c.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -arch arm64 -mmacosx-version-min=10.9 -MD -MT CMakeFiles/cmTC_560a4.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_560a4.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_560a4.dir/testCCompiler.c.o -c /Users/.../Documents/Proyects/BarrierNative/orignial/barrier/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_560a4
    /opt/homebrew/Cellar/cmake/3.20.5/bin/cmake -E cmake_link_script CMakeFiles/cmTC_560a4.dir/link.txt --verbose=1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -arch arm64 -mmacosx-version-min=10.9 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/opt/homebrew/opt/qt@5/lib  CMakeFiles/cmTC_560a4.dir/testCCompiler.c.o -o cmTC_560a4
    ld: library not found for -lSystem
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_560a4] Error 1
    make: *** [cmTC_560a4/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
 CMakeLists.txt:19 (project)
```

---

> Commented on: 2021-11-05 by @shymega

Related to #1385 - let's continue the discussion there for now.

---

> Closed on: 2021-11-05

### CODE REVIEW

**Comment by Am0rphous** [comment]
Hi!
Using macOS Ventura 13.3.1 (a), this bug seems to persist.

To repreduce: Follow standard instructions for installing input-leap on [macOS](https://github.com/input-leap/input-leap/wiki/Building-on-macOS).
````
brew install qt5 openssl pkg-config
#OR: sudo port install qt5 openssl pkgconfig

git clone https://github.com/input-leap/input-leap
cd input-leap
./clean_build.sh
````
Produces the error:
````
./clean_build.sh 
Modifying environment for Barrier build...done
Starting Barrier Debug build...
CMake Warning at /usr/local/Cellar/cmake/3.26.3/share/cmake/Modules/Platform/Darwin-Initialize.cmake:303 (message):
  Ignoring CMAKE_OSX_SYSROOT value:

   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk

  because the directory does not exist.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.26.3/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:19 (project)


-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - broken
CMake Error at /usr/local/Cellar/cmake/3.26.3/share/cmake/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/Library/Developer/CommandLineTools/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/user/Downloads/input-leap-2.1.0/build/CMakeFiles/CMakeScratch/TryCompile-51cVIJ
    
    Run Build Command(s):/usr/local/Cellar/cmake/3.26.3/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_0cb33/fast && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_0cb33.dir/build.make CMakeFiles/cmTC_0cb33.dir/build
    Building C object CMakeFiles/cmTC_0cb33.dir/testCCompiler.c.o
    /Library/Developer/CommandLineTools/usr/bin/cc   -mmacosx-version-min=10.9 -MD -MT CMakeFiles/cmTC_0cb33.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_0cb33.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_0cb33.dir/testCCompiler.c.o -c /Users/user/Downloads/input-leap-2.1.0/build/CMakeFiles/CMakeScratch/TryCompile-51cVIJ/testCCompiler.c
    Linking C executable cmTC_0cb33
    /usr/local/Cellar/cmake/3.26.3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0cb33.dir/link.txt --verbose=1
    /Library/Developer/CommandLineTools/usr/bin/cc  -mmacosx-version-min=10.9 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_0cb33.dir/testCCompiler.c.o -o cmTC_0cb33 
    ld: library not found for -lSystem
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_0cb33] Error 1
    make: *** [cmTC_0cb33/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)

-- Configuring incomplete, errors occurred!
````

Someone [said](https://stackoverflow.com/questions/65465972/ld-library-not-found-for-lsystem-macos-big-sur-11-1) `brew reinstall gcc && brew reinstall gfortran` would fix this, but this only gives a bit smaller error.
````
CMake Error at /opt/local/share/cmake-3.24/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/Library/Developer/CommandLineTools/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/user/Downloads/input-leap-2.1.0/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_4c1d2/fast && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_4c1d2.dir/build.make CMakeFiles/cmTC_4c1d2.dir/build
    Building C object CMakeFiles/cmTC_4c1d2.dir/testCCompiler.c.o
    /Library/Developer/CommandLineTools/usr/bin/cc   -mmacosx-version-min=10.9 -MD -MT CMakeFiles/cmTC_4c1d2.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_4c1d2.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_4c1d2.dir/testCCompiler.c.o -c /Users/user/Downloads/input-leap-2.1.0/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_4c1d2
    /opt/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4c1d2.dir/link.txt --verbose=1
    /Library/Developer/CommandLineTools/usr/bin/cc  -mmacosx-version-min=10.9 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_4c1d2.dir/testCCompiler.c.o -o cmTC_4c1d2 
    ld: library not found for -lSystem
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_4c1d2] Error 1
    make: *** [cmTC_4c1d2/fast] Error 2
    
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:19 (project)

-- Configuring incomplete, errors occurred!
````
Btw: It seems installing it with macports gives a successfull install: ` sudo port install input-leap `

**Comment by shymega** [comment]
You reinstalled macOS? It looks like your version of XCode doesn't have the correct SDK installed.

**Comment by Am0rphous** [comment]
No I meant I tried reinstalling XCode.

**Comment by shymega** [comment]
OK. I think you're missing the correct SDK. The CMake error does indicate this.

**Comment by Ifeinstein** [comment]
`sudo ln -s /Applications/Xcode.app/Contents/Developer/Platforms /Library/Developer/CommandLineTools/Platforms`
This might help, the SDK's path has been changed

**Comment by shymega** [comment]
That may be useful. Do you think it's worth putting in the wiki, or the `clean_build.sh` script? I'm wondering whenever both might work.

**Pull request closed without merging**
