### PR TITLE
about.png changed to InputLeap

### PR DESCRIPTION
**Pull request by aekoroglu**
Until someone makes it better :)

### CODE REVIEW

**Comment by shymega** [comment]
@aekoroglu Could you please remove those AppData commits and push again? We already merged that, and I don't want unnecessary reverts and commits in mainline. Also, #1618 might conflict with this PR.

**Comment by aekoroglu** [comment]
I changed the logo with the one and rebase my commits

**Comment by shymega** [comment]
Thanks, waiting for @p12tic to approve now.

**Comment by shymega** [comment]
Going to merge this now. We need to get a v3.0.0 release out soon, and this PR paves the way.

**Pull request merged**
