### PR TITLE
Handle super modifier in EiKeyState

### PR DESCRIPTION
**Pull request by wav**
## Contributor Checklist:

* [x] I have created a file in the `doc/newsfragments` directory *IF* it is a
      user-visible change (and make sure to read the `README.md` in that directory)

### CODE REVIEW

**Review by p12tic — APPROVED** [review]
LGTM, but please add a newsfragment

**Comment by shymega** [comment]
> LGTM, but please add a newsfragment

Does the newsfragment look good to you? I'm finding it a tad sparse.

**Comment by p12tic** [comment]
> Does the newsfragment look good to you? I'm finding it a tad sparse.

I think this newsfragment is enough

**Comment by p12tic** [comment]
> I think this newsfragment is enough

However, it is always possible to suggest specific improvements.

**Pull request merged**
