### PR TITLE
Miscellaneous warnings

### PR DESCRIPTION
**Pull request by mokibit**
This PR fixes miscellaneous C++ warnings.

### CODE REVIEW

**Comment by shymega** [comment]
Asking @p12tic for input on this PR. Thanks for your contribution! I'm actually working on getting this project ready for a first release and continued development.

Builds look promising so far. I hope to see this merged!

**Comment by shymega** [comment]
You need to really use the template though. There's a checkbox in the template for the newsfragment requirement, but if these are just lint fixes, I don't think it'll matter too much - the newsfragment is for *user-visible* changes. I.e, GUI or translations.

**Review by p12tic — APPROVED** [review]

**Comment by mokibit** [comment]
@shymega thanks for comment, next PR will be better. This time it is only fixing the warnings and not visible to users.

**Comment by shymega** [comment]
> @shymega thanks for comment, next PR will be better. This time it is only fixing the warnings and not visible to users.

No worries. Normally the template is applied, so I'm not sure why it's not here. Merging now, as Povilas has approved, and all checks passed.

**Comment by mokibit** [comment]
@shymega oh, the template is not here because I deleted it.  Thanks for merging.

**Comment by shymega** [comment]
OK, so in future, you should really keep the template, it's there for a reason. No problem for merging, we appreciate the contribution!

**Pull request merged**
