### PR TITLE
Continue renaming from Barrier to InputLeap

### PR DESCRIPTION
**Pull request by shymega**
This commit adds to @p12tic's commit (hash: cdda053d) of changing
Debauchee and Barrier references to the new InputLeap project.

I've adjusted the developer group name of "Debauchee Open Source Group"
to "The InputLeap Developers", and renamed the URLs to the new InputLeap
organisation and repository.

With regards to the newsfragment: I'm not sure if it's worth creating one until we have fully renamed all Barrier + Debauchee references, as this commit does *not* fix all references yet. There's still some in translations and codebase (But the latter isn't always user-facing). I'd personally like to make a final newsfragment once everything has been changed.

Additionally: we need to be sure of the new name. It's not clear if it's "InputLeap" OR "Input-Leap". I'll be making a edit to the README and Wiki soon.

Signed-off-by: Dom Rodriguez <shymega@shymega.org.uk>

## Contributor Checklist:

* [ ] I have created a file in the `doc/newsfragments` directory *IF* it is a
      user-visible change (and make sure to read the `README.md` in that directory)

### CODE REVIEW

**Comment by p12tic** [comment]
> With regards to the newsfragment: I'm not sure if it's worth creating one until we have fully renamed all Barrier + Debauchee references, as this commit does not fix all references yet. There's still some in translations and codebase (But the latter isn't always user-facing). I'd personally like to make a final newsfragment once everything has been changed.

Agreed.

**Review by p12tic — APPROVED** [review]

**Comment by p12tic** [comment]
> Additionally: we need to be sure of the new name. It's not clear if it's "InputLeap" OR "Input-Leap". I'll be making a edit to the README and Wiki soon.

I think maybe InputLeap looks better?

**Comment by shymega** [comment]
> > Additionally: we need to be sure of the new name. It's not clear if it's "InputLeap" OR "Input-Leap". I'll be making a edit to the README and Wiki soon.
> 
> I think maybe InputLeap looks better?

Well, I think 'Input Leap' for the application name, `INPUTLEAP` or `inputleap` for CMake vars and C++ codebase, and then `Input-Leap` for the Git stuff. 'InputLeap' for the name looks a bit crowded.

We could do a poll in the Discussions area, and have it done by reactions. Do you want me to initiate that? Once we've decided, I can do a mass PR changing the existing changes we've made via PRs to the decided name.

Thoughts?

**Comment by shymega** [comment]
@p12tic Did you decide on the poll idea? :)

**Comment by donuts-are-good** [comment]
Folks, let's move this along.

**Comment by shymega** [comment]
> Folks, let's move this along.

It still needs to be addressed though - a consistent name is necessary.

**Comment by shymega** [comment]
@p12tic Did you see the above comment? I think we should still do a branch, and a recent Reddit post has noticed that we haven't decided on the final name for this fork, so we do need to make a decision, otherwise, it doesn't look as appealing as Barrier. Cross-posting here...

**Comment by earthsound** [comment]
I created [a poll in the Discussions area](https://github.com/input-leap/input-leap/discussions/1470) to vote for a name.

**Pull request merged**
