### PR TITLE
Run find/replace on translations

### PR DESCRIPTION
**Pull request by shymega**
This is a bit hacky, but I ran `sed` on the translations, to change
'Barrier' to 'Input Leap', etc.

It seems to compile fine, but I haven't yet tested translations, as I'm
only fluent in English, unfortunately.

There are still references to `barriers` and `barrierc`, but we haven't
renamed those yet, so this will need more work.

Signed-off-by: Dom Rodriguez <shymega@shymega.org.uk>

## Contributor Checklist:

* [x] I have created a file in the `doc/newsfragments` directory *IF* it is a
      user-visible change (and make sure to read the `README.md` in that directory)

### CODE REVIEW

**Comment by shymega** [comment]
Actually, I'm going to convert this to a draft. That way, we can continue the work on renaming `barriers` and `barrierc` - if you disagree @p12tic, we can revert that conversion.

**Comment by p12tic** [comment]
@shymega barriers and barrierc conversion will need more work because we want to migrate the configuration automatically. I think let's limit this PR to translations only.

**Comment by p12tic** [comment]
@shymega PR LGTM.

I think commit title is a bit unclear right now: "Run find/replace on translations" does not say what we are replacing. Something like "Rename Barrier to Input Leap in translations" would be better.

**Review by p12tic — APPROVED** [review]

**Comment by shymega** [comment]
Just renamed.

**Pull request merged**
