### PR TITLE
Release fixes

### PR DESCRIPTION
**Pull request by p12tic**
Miscellaneous release-related fixes

### CODE REVIEW

**Comment by sithlord48** [comment]
There is No reason to release the Qt5 windows build.. Or really even to have a Qt5 windows build at this point.

**Comment by p12tic** [comment]
Several percent users still use Windows 7 and similar cruft. Let them have this last release and then we can remove Qt5 support.

**Comment by sithlord48** [comment]
> Several percent users still use Windows 7 and similar cruft. Let them have this last release and then we can remove Qt5 support.

They can and should use barrier..

**Comment by p12tic** [comment]
I don't see problems if the release contains Qt5 windows though.

**Pull request merged**
