### PR TITLE
Clarify README to accurately explain status of project

### PR DESCRIPTION
**Pull request by shymega**
After some confusion on the status of Input Leap (#1696), I took the liberity of editing the README to be more accurate.

## Contributor Checklist:

* [ ] I have created a file in the `doc/newsfragments` directory *IF* it is a
      user-visible change (and make sure to read the `README.md` in that directory)

### CODE REVIEW

**Comment by m10d** [comment]
@shymega Thank you for creating this.  The edits here are perfectly clear.  

The only thing I would add:  note that what happened in my case was:

1) read that `input-leap` is the new way, so decided to migrate after [one too many hangs](https://github.com/debauchee/barrier/issues/1936#issuecomment-1543281126) with `barrier`
2) found & built the server, expecting to either get `input-leap` client going somehow on my windows PC, or just keep windows on barrier per https://github.com/input-leap/input-leap/issues/1414
3) obviously per the other discussion, neither of those ended up working.

Now, I wouldn't have done that after your clarifying edits in this PR, but perhaps it's worth mentioning in the readme that `input-leap` is *not* expected to be barrier compatible at this time.

Anyway, appreciate your work, thanks for updating this!

**Comment by m10d** [comment]
@shymega @abienz

Since the [original discussion](https://github.com/input-leap/input-leap/discussions/1696) is locked (understandably) due to user behavior, I wanted to add my 2c here since it's supportive.  Perhaps those users will see this reference and read it, it would do them good.  The other users on that thread were quite out of line.  

Further (and critically), we can even ignore civility which could be subjective and just lean on logic:

1. we should hold people accountable to their commitments.  But in this case, as best I can tell, the maintainers of `input-leap` have committed to:
    1. be the maintainers of `input-leap`
1. **that's it**.  This doesn't imply a schedule, it doesn't imply certain functionality (except as they communicate it)

About the only true commitments here are:

- for the `input-leap` maintainers to publish accurate information about their intentions (_hopefully_ that includes a best-guess on release schedule ... but it's a guess not a commitment, and perhaps it's just "we have no idea")
- to make sure people know if they are going to disengage and be helpful in updating any `abandoned` repo as such (man, literally no one does this, WTH; eg `barrier`)
- to be reasonably responsive to users if their project is meant for general consumption, with the "until proven wrong" assumption / mutual-gratitude that the users are trying to make minor contributions to the project via bug reports, testing, etc.  

This `PR` seems to satisfy all that in this case.

And on a side note, thank you for continuing this project.  I really appreciate having a `does one thing and does it well & securely` software KVM.

**Comment by m10d** [comment]
and leaving as a separate comment since the feedback about is most important given the recent "discussions"  - I would as a user definitely vote for smaller / incremental releases in the future (eg, playing armchair qb, release the rename before the large refactor/3.0).  But that ship sailed, I'm sure you might have come to the same conclusion, but it's all in the past now.  And a volunteer project. 

also, the whole azure thing - sounds like you're migrating off that, but who cares, anyway?  The CI/CD is for quality and usability _for developers_.  It's ridiculous to try to conflate that concept with whether or not releases _exist_ or not.  The user's issue was with the presence of releases, not what the infrastructure is.

keep calm, carry on :)  thanks again.

**Comment by krwudtke** [comment]
Yes, this clarifies things greatly. Please get it published ASAP! 
(Spare other people the frustration that I felt with links to releases going nowhere, etc.)

**Comment by shymega** [comment]
> @shymega Thank you for creating this. The edits here are perfectly clear.
> 
> The only thing I would add: note that what happened in my case was:
> 
> 1. read that `input-leap` is the new way, so decided to migrate after [one too many hangs](https://github.com/debauchee/barrier/issues/1936#issuecomment-1543281126) with `barrier`
> 2. found & built the server, expecting to either get `input-leap` client going somehow on my windows PC, or just keep windows on barrier per [Active Barrier maintainers have moved here #1414](https://github.com/input-leap/input-leap/issues/1414)
> 3. obviously per the other discussion, neither of those ended up working.
> 
> Now, I wouldn't have done that after your clarifying edits in this PR, but perhaps it's worth mentioning in the readme that `input-leap` is _not_ expected to be barrier compatible at this time.
> 
> Anyway, appreciate your work, thanks for updating this!

I can add that, but I think the intention is to keep it Barrier-compatible. Problem is, we've made several changes, and not every Barrier bug is valid now. So maybe we could add this in a later iteration of the README.

**Comment by shymega** [comment]
> Since the [original discussion](https://github.com/input-leap/input-leap/discussions/1696) is locked (understandably) due to user behavior, I wanted to add my 2c here since it's supportive. 

Thank you :+1:

> Perhaps those users will see this reference and read it, it would do them good. The other users on that thread were quite out of line.

Just wanted to clarify this: we're not talking about the users who supported the project, right? I figured you meant what I thought you meant - i.e, the user who got their comments hidden. But just wanted to check, because I felt the users who were on the side of Input Leap were reasonable. My mistake if I misinterpreted you.
 
> Further (and critically), we can even ignore civility which could be subjective and just lean on logic:
> 
> 1. we should hold people accountable to their commitments.  But in this case, as best I can tell, the maintainers of `input-leap` have committed to:
>    
>    1. be the maintainers of `input-leap`
> 2. **that's it**.  This doesn't imply a schedule, it doesn't imply certain functionality (except as they communicate it)
> 
> About the only true commitments here are:
> 
> * for the `input-leap` maintainers to publish accurate information about their intentions (_hopefully_ that includes a best-guess on release schedule ... but it's a guess not a commitment, and perhaps it's just "we have no idea")
> * to make sure people know if they are going to disengage and be helpful in updating any `abandoned` repo as such (man, literally no one does this, WTH; eg `barrier`)
> * to be reasonably responsive to users if their project is meant for general consumption, with the "until proven wrong" assumption / mutual-gratitude that the users are trying to make minor contributions to the project via bug reports, testing, etc.
> 

Agreed, here. We never set out any contractual obligations. I think a fair amount of users do believe open-source is a right for them to have, which is why I responded like I had.

> This `PR` seems to satisfy all that in this case.

Thank you, I think it's pretty much ready to merge now!

> And on a side note, thank you for continuing this project. I really appreciate having a `does one thing and does it well & securely` software KVM.

Thank you, again. I'm looking at rewriting some internal stuff with Rust, but I'm not too sure yet. That should be a seamless change, though. Users shouldn't notice it if they use packages.

**Comment by shymega** [comment]
> and leaving as a separate comment since the feedback above is most important given the recent "discussions" - I would as a user definitely vote for smaller / incremental releases in the future (eg, playing armchair qb, release the rename before the large refactor/3.0). But that ship sailed, I'm sure you might have come to the same conclusion, but it's all in the past now. And a 
volunteer project.

This is something I've been pushing towards. I would rather make small semver releases, than big releases. I think a lot of it is time-related.

> also, the whole azure thing - sounds like you're migrating off that, but who cares, anyway? The CI/CD is for quality and usability _for developers_. It's ridiculous to try to conflate that concept with whether or not releases _exist_ or not. The user's issue was with the presence of releases, not what the infrastructure is.

I've merged the GitHub Actions PR now, and would especially like to migrate off Azure. Releases should be able to be built by GH Actions, ideally, but yeah - it was a bit of a weird conflation. In any case, the user in question has been banned from the organisation.

> 
> keep calm, carry on :) thanks again.

:)

**Comment by shymega** [comment]
> Yes, this clarifies things greatly. Please get it published ASAP! (Spare other people the frustration that I felt with links to releases going nowhere, etc.)

Yes, I edited it a bit more tonight. Probably will merge it before bed. I've added comments to edit parts of the README in the future.

**Comment by shymega** [comment]
I'm going to assign this to @p12tic for review, and then we can merge. @p12tic is very busy right now, so if we don't hear back by say, next Thursday, I'll go ahead and merge without review, due to the need for a clearer README.

**Comment by shymega** [comment]
@the-wes Feel free to review or give your thoughts, too. :)

**Comment by shymega** [comment]
> > Just wanted to clarify this: we're not talking about the users who supported the project, right? I figured you meant what I thought you meant - i.e, the user who got their comments hidden. But just wanted to check, because I felt the users who were on the side of Input Leap were reasonable. My mistake if I misinterpreted you.
> 
> That's correct.

OK, great. Sorry to add any doubt - I just wanted to make sure I read it correctly. Again, thank you so much for your support :)

**Review by p12tic — APPROVED** [review]

**Pull request merged**
