### PR TITLE
build: remove unused curl dependency

### PR DESCRIPTION
**Pull request by sithlord48**
## Contributor Checklist:

* [ ] This change affects end users and I have created a file in the `doc/newsfragments` directory (and made sure to read the `README.md` in that directory)
* [X] This change does not affect end users

Clean up unneeded dependencies

 - Remove unneeded `curl`

### CODE REVIEW

**Comment by nbolton** [comment]
I can't remember for the life of me why the CURL dep was added. I think because at some stage the GUI would download and install Bonjour from Apple, but it was like 15 years ago.

**Comment by shymega** [comment]
I think the commit msg should explain the justification for the change, and also 'depencency' => 'dependency'. Other than that, I have zero objections.

**Review by shymega — APPROVED** [review]
LGTM, and good to have one less dep. Thanks!

**Comment by nbolton** [comment]
> I think the commit msg should explain the justification for the change

Agreed.

**Comment by shymega** [comment]
> > I think the commit msg should explain the justification for the change
> 
> Agreed.

Yeah, I merged after the last amendment, but I think, in future, we should justify commit messages. A one-liner is quite vague.

**Comment by sithlord48** [comment]
I don't understand what you guys mean by justification . `Unused dependency` to me is the justification for removing it. What would a proper message for this be so i know for the future ?

**Comment by nbolton** [comment]
> What would a proper message for this be so i know for the future ?

Good question. I was speaking in general terms, and perhaps in this particular case... what more can you say? I'm struggling to think of an example, to be honest.

**Comment by sithlord48** [comment]
> I think justification was the wrong word I used for this. In short, I got hung up on the commit message, and was nit-picking. Perhaps, in future, we should decide on a case-by-case basis - but the main criteria I generally have for my personal standards are:
> 
>     * Context for the change - i.e, why change X, does it have breaking changes, is there any related PRs/issues that will be fixed, or depend on the change?
> 
>     * Imperative commit messages.
> 
>     * Scope of the change.
> 
>     * Correct grammar and spelling.
> 
> 
> Perhaps we should document this on the wiki, if these are a good baseline for contributors.

Yes i would make a contributing document.

**Pull request merged**
