### PR TITLE
build: remove stale build scripts

### PR DESCRIPTION
**Pull request by sithlord48**
## Contributor Checklist:

* [ ] This change affects end users and I have created a file in the `doc/newsfragments` directory (and made sure to read the `README.md` in that directory)
* [X] This change does not affect end users

Fixes: #1950 

Matching Wiki Update: https://github.com/input-leap/wiki-prs/pull/14

### CODE REVIEW

**Comment by mikehardy** [comment]
Wow! --> https://github.com/input-leap/wiki-prs/pull/14/files

This is fantastic, in cliche "user story" terms, "As a developer trying to build the project for the first time, I want detailed build information"

Nailed that, for sure. Thanks!

**Comment by p12tic** [comment]
@shymega Could you please wait for a few days for a review? This breaks my workflow.

**Comment by shymega** [comment]
@p12tic I was in a position where I had to get some PRs merged. It wasn't clear when you were going to be around for a review - sometimes it can be a while.

**Comment by shymega** [comment]
It also looks bad on me. I'm trying to keep this project alive, and when I have to await for review, for sometimes, simple PRs, and I have to say' OK, we have to wait for review', it leads - conclusively - to discontent and dissatisfaction.

I would like to add some more maintainers to the project. I am starting a new job very soon, and I fear the project will become stale.

**Pull request merged**
