### PR TITLE
Fix Debian packaging scripts

### PR DESCRIPTION
**Pull request by shymega**
This is applied from @draekko's Gist from issue #1602, which I've turned into a PR.

Thank you!

## Contributor Checklist:

* [ ] I have created a file in the `doc/newsfragments` directory *IF* it is a
      user-visible change (and make sure to read the `README.md` in that directory)

### CODE REVIEW

**Comment by p12tic** [comment]
This undoes some of the things I wanted to have in the package, I will look in the PR deeper, test it and fix the issues.

**Comment by draekko** [comment]
@shymega  This PR worked for me.

@p12tic The original patch provides all the files needed to a user to use input-leaf from the provided package,  what's missing?

**Comment by shymega** [comment]
> This undoes some of the things I wanted to have in the package, I will look in the PR deeper, test it and fix the issues.

Could you expand on this Povilas? I didn't see anything that was particularly bad with the patch, but I'd be interested to hear your thoughts on it. I mean, we are technically leaving packaging up to distro-specific maintainers; this is just an scaffold, so it might not even be final in distros.

**Comment by shymega** [comment]
> @shymega This PR worked for me.
> 
> @p12tic The original patch provides all the files needed to a user to use input-leaf from the provided package, what's missing?

Cool, thanks for testing.

**Comment by shymega** [comment]
Sorry all, during housekeeping, I thought this branch had been merged, and thus deleted it on my fork by accident. @p12tic Your views are still required here.

**Review by p12tic — APPROVED** [review]

**Pull request merged**
