### PR TITLE
Changed Server IP shortcut to not conflict with Start/Stop

### PR DESCRIPTION
**Pull request by Trial97**
## Contributor Checklist:

* [x] This is a user-visible change and I have created a file in the `doc/newsfragments` directory (and made sure to read the `README.md` in that directory)
* [ ] This is not a user-visible change

### CODE REVIEW

**Comment by shymega** [comment]
I do not understand the need for this PR. Why have you put a `&amp;` between 'I' and 'P'?

When it's ready to be merged (if), then the two commits should be squashed.

**Comment by Trial97** [comment]
The QT framework allows you to define shortcuts by adding an `&amp;` before the letter you want to use as a shortcut.
Right now the shortcut for the `Start`/`Stop` button conflicts with the `Server IP` one.
When I use server configuration the shortcut `Alt+S` starts and stops the input leap, but when I use client configuration using the same shortcut only selects the `Server IP` input.
This change replaces that shortcut from  `Server IP` with `Alt+P` (from what I saw it was not used on that dialog) and makes the `Start`/`Stop` shortcut consistent between server and client configuration.
As a bonus, I tried to make the translations use the same shortcut for `Server IP`.

**Comment by shymega** [comment]
Apologies! I'm not involved with Qt on this project, and I've been doing a **lot** of HTML recently. I'll await for @p12tic to review, and then we can get this merged.

**Comment by shymega** [comment]
Merging without review, want to get a release out of the door.

**Pull request merged**
