### PR TITLE
gui: Update Hungarian translation

### PR DESCRIPTION
**Pull request by p12tic**
This is a port of https://github.com/debauchee/barrier/pull/1458 to input-leap.

Thanks @ViBE-HU.

## Contributor Checklist:

* [x] I have created a file in the `doc/newsfragments` directory *IF* it is a
      user-visible change (and make sure to read the `README.md` in that directory)

### CODE REVIEW

**Comment by p12tic** [comment]
@ViBE-HU feel free to close https://github.com/debauchee/barrier/pull/1458 on the Barrier repo, it's unlikely that significant development effort will pick up there as the most active maintainers have moved here (see https://github.com/input-leap/input-leap/issues/1414).

**Comment by ViBE-HU** [comment]
please help me understand cause i'm not a professional. i do translations and report bugs mostly on github and now i'm a bit confused how forks works on github. so my issue/request is useless or just i did it on the wrong repo/fork(?)

**Comment by p12tic** [comment]
@ViBE-HU You did everything alright. There was a disagreement between Barrier developers which has lead to a split. The most active developers decided to leave and develop Barrier independently with InputLeap name. You can read more about this here (https://github.com/input-leap/input-leap/issues/1414).

I saw your pull request on the old repository and copied it here. In the future it would be best to do pull requests here as the original Barrier will become non-maintained anyway.

**Comment by ViBE-HU** [comment]
oh okay. but the newer releases will appears here or still on the original barrier repo?

**Comment by shymega** [comment]
> oh okay. but the newer releases will appears here or still on the original barrier repo?

It depends on which repository you use. We're the fork of Barrier -- InputLeap. You can expect to have releases here. As for the Barrier repository, it's impossible for me to say, but given @p12tic and I were the active developers/maintainers, I'd hazard a guess that Barrier wouldn't be as active now.

It's up to you really. I just wanted to reply to you here, and explain further.

I hope that clarifies things for you further :)

**Comment by ViBE-HU** [comment]
> > oh okay. but the newer releases will appears here or still on the original barrier repo?
> 
> It depends on which repository you use. We're the fork of Barrier -- InputLeap. You can expect to have releases here. As for the Barrier repository, it's impossible for me to say, but given @p12tic and I were the active developers/maintainers, I'd hazard a guess that Barrier wouldn't be as active now.
> 
> It's up to you really. I just wanted to reply to you here, and explain further.
> 
> I hope that clarifies things for you further :)

i can support both but my goal is to give native language support for the better KVM option. if Barrier is dying then i would continue with InputLeap, cause it's a priority for my home office. it just wasn't clear where to report or contact. btw when the first release arrive? also: **will be PPA available for it? it's important.**

**Comment by shymega** [comment]
I would continue with InputLeap. Here is a good place to report or contact. You'd be best asking @p12tic about the first release, but I would probably manage CI sort of things like I did in Barrier - @p12tic, is that OK? We can discuss on IRC if you want.

**Pull request merged**
