### PR TITLE
Make Qt6 the default

### PR DESCRIPTION
**Pull request by sithlord48**
## Contributor Checklist
 * [ ] This is a user-visible change and I have created a file in the doc/newsfragments directory (and made sure to read the README.md in that directory)
* [x] This is not a user-visible change

- Build with Qt6 by default
- Does not change snap or flatpak formulas

### CODE REVIEW

**Comment by shymega** [comment]
Not sure how I feel about this. I would rather not make Qt 6 the default at this time.

Also, please keep the PR template intact - the bot I'm toying with creating to manage triage, won't play nicely with edits to the template.

**Comment by Goddard** [comment]
Tested and working great.

Operating System: openSUSE Tumbleweed 20240506
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0
Kernel Version: 6.8.8-1-default (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 7950X3D 16-Core Processor
Memory: 30.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4090/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X670E AORUS PRO X
System Version: -CF

**Comment by shymega** [comment]
Assigned review to @p12tic. PR now pending review.

**Comment by shymega** [comment]
@p12tic Please can we get a review going here? I'd like to issue a release. Working on a milestone for it.

**Comment by shymega** [comment]
No reply from @p12tic, going to merge this. This project appears too slow to merge to external users, thus stifling contributions. It cannot go on.

**Pull request merged**
