### PR TITLE
A few ei fixes again

### LINKED ISSUE #1871: Cursor disapearing and input not going anywhere after moving offscreen.
### What happened?

Starting with commit [650ce407d974baf856b9a1a1298c3c6252b33e93](https://github.com/input-leap/input-leap/commit/650ce407d974baf856b9a1a1298c3c6252b33e93) when I attempt to move my cursor to my client screen it  disappears.  At that point all input is lost and can not be regained.  I have to ssh into my server and kill the input-leaps service to get my input back.

GNOME Linux server (libei) > Windows 10 client

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

650ce407d974baf856b9a1a1298c3c6252b33e93

### If applicable, where did you install Input Leap from?

self-built

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland

### What OS versions are you using?

Arch Linux server & Windows 10 client

### Relevant log output

_No response_

### Any other information

_No response_

### PR DESCRIPTION
**Pull request by whot**
Three fixes necessary for the ei client/server to work a bit less buggily. 

Third commit fixes #1871

## Contributor Checklist:

* [ ] This is a user-visible change and I have created a file in the `doc/newsfragments` directory (and made sure to read the `README.md` in that directory)
* [x] This is not a user-visible change

### CODE REVIEW

**Review by shymega — COMMENTED** [review]
LGTM, but I do have a query - what's with the variable names ending with an underscore? It seems somewhat out of consistency with the rest of IL.

**Comment by whot** [comment]
> what's with the variable names ending with an underscore? 

It's for member variables, same as the `m_foo` and it's used quite commonly[^1]:

```
$  git grep -e "\<\w\+_\>" -l | wc -l
160
$  git grep -e "\<m_\w\+\>" -l | wc -l
281
```
So the `m_foo` is more common than `foo_` but it's not a new thing. Obviously that regex is not 100% accurate but it's close enough.

[^1]: I also have a very vague recollection of @p12tic telling me that this is preferred now but I'm not sure whether this actually happened or whether my mind made this up...

**Review by p12tic — APPROVED** [review]

**Comment by p12tic** [comment]
Thanks for the PR!

**Comment by p12tic** [comment]
> I also have a very vague recollection of @p12tic telling me that this is preferred now but I'm not sure whether this actually happened or whether my mind made this up... [↩](https://github.com/input-leap/input-leap/pull/1878#user-content-fnref-1-7a5b456cd9c2a9ad9c7b125eb3851137)

This is correct. cc @shymega

**Pull request merged**
