### PR TITLE
Update Qt6 changes to avoid anchoredPattern

### PR DESCRIPTION
**Pull request by Cimbali**
## Contributor Checklist:

* [ ] I have created a file in the `doc/newsfragments` directory *IF* it is a
      user-visible change (and make sure to read the `README.md` in that directory)

### CODE REVIEW

**Comment by shymega** [comment]
I think it would have been less confusing to put a patch in #1469, then asked the original author if this works. The problem now is that we have two PRs, both for Qt6, and implementing the same, with one different line, code. I'm gonna close this issue, and export c48bc3ca - then post that in #1469.

Sorry about this.

**Comment by shymega** [comment]
Sorry, two different changes. Didn't see you pushed before I hit submit on my comment. So now, I'll export both commits. Might be best to continue this on #1469.

**Comment by Cimbali** [comment]
No worries @shymega! I just can't suggest the change on the other PR myself (I left a comment but can't do more). In any case this PR servies to show the CI runs.

Also I forgot to add the `$` see https://github.com/input-leap/input-leap/pull/1667/commits/04bb0777e8058ef1f9a66fd651200eb68c73014e

**Comment by shymega** [comment]
Oh, I thought you could make comments, or review - sorry about this. Comments are welcome. I think only maintainers can make changes to the PR's branch.

**Pull request closed without merging**
