### PR TITLE
clean_build: Use cmake --build . --parallel

### PR DESCRIPTION
**Pull request by p12tic**
This ensures that the all CPU cores are used without introducing any non-portable scripting.

### CODE REVIEW

**Review by shymega — APPROVED** [review]
Looks fine to me. Liking the way it doesn't rely on `make` now.

**Comment by shymega** [comment]
Actually, just one thing - what compatibility does this change impose on older versions of CMake? That's my one concern, other than that I have no objections.

**Comment by p12tic** [comment]
Our requirements are CMake 3.4 (see CMakeLists.txt), which according to the docs already had --build command.

**Comment by albertony** [comment]
But not --parallel until [3.12](https://cmake.org/cmake/help/v3.12/release/3.12.html).

**Comment by shymega** [comment]
> But not --parallel until [3.12](https://cmake.org/cmake/help/v3.12/release/3.12.html).

Yeah, that was my concern too.

**Comment by albertony** [comment]
3.12 came out july 2018, so bumping minimum requirement to that should not be too controversial...

**Comment by p12tic** [comment]
Hm, indeed, I should have checked --parallel too.

Though this is not actually real minimum requirement on CMake version. clean_build.sh is just a convenience script.

**Comment by shymega** [comment]
That's true, it's only in the script. For package maintainers, I don't see much of an issue -- they have their own processes, which are usually quite robust -- and bumping the requirement as @albertony rightly points out won't be too much trouble.

**Pull request merged**
